packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@supabase/supabase-js": ^2.105.1
  "@types/node": ^24
  tslib: ^2.8.1
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
