packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@supabase/supabase-js": ^2.105.1
  "@tiptap/core": ^3.22.5
  "@tiptap/extension-color": ^3.22.5
  "@tiptap/extension-font-family": ^3.22.5
  "@tiptap/extension-heading": ^3.22.5
  "@tiptap/extension-image": ^3.22.5
  "@tiptap/extension-link": ^3.22.5
  "@tiptap/extension-placeholder": ^3.22.5
  "@tiptap/extension-text-align": ^3.22.5
  "@tiptap/extension-text-style": ^3.22.5
  "@tiptap/extension-underline": ^3.22.5
  "@tiptap/pm": ^3.22.5
  "@tiptap/react": ^3.22.5
  "@tiptap/starter-kit": ^3.22.5
  "@types/dompurify": ^3.2.0
  "@types/node": ^24
  dompurify: ^3.4.2
  tslib: ^2.8.1
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
